on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
              ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.10.0
          run_install: true
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Build
        run: pnpm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
